travis:
  secure:
    BINSTAR_TOKEN: RKs+xmwxL5h9inJsGMc9R5T+h9qqTSF39UH17kXjDQ+07rqEPl3vfQ5TnRcdKxMNSrLjP/tsx9mmbX4xBQhqavp0MGWtM/KLH3vhdGcegFFrYLLkAB7YICKrWfDQZ+Kl6NmjFD48uVGyvVu5WcbPOKJshtvVOa8T/ky4Ev3Xvh1kjbmNiulKMHTcIIgJUtb0O9CbrBimuHU+b57BONv48/OHZNEqADqeDHzYSdX5BGa0ZUGqi0J/D2NgcJ9v57pND7lkUPF1Zmvdir8Iqd2iOY21Y/XIT4c+thZsiAdWazmxElCbk8tZ3WpNGjiT35QTzlGx1R3Ev1COuTagktp6fJrPs7s42PpQMTraJEmRTPqdfhR+T7vClZZzZIMMFtf2CvPA2DgU3XLARRMtzuCYgzedarj5veRly5gsR+jX3il5OhghfQagILiaRWjRZGMaWxe+07lHnTTxeYzAukrXnOf2n4ctbjMbDTLxjVvOmirtFG00zInfLPXfV0yJsqGTBlcNnLTdLMeVYAerHOBgnpGvmp8tey8vA9nUapKiT1Z0eTFJJGv5YrZrsV/ew5kWMcSyfyar7cpJUh7hEfM2ZPQHG6/oM/2AjhZ5Soaq1vzOgSWKA5iiDiu0Iv2AncgJtQCbV+Fha2SpB+LNdbPtAyxJSN0NPvCF5uU5g3AIJa0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
